### ISSUE TITLE
Pip installation not working

### ISSUE THREAD

**Issue by crockwell** [danini/magsac#31]
Hi,

Thanks for your great work on magsac. I am trying to install magsac using pip and python 3.8. Per the pip output, I successfully installed `pymagsac==0.2.0`. I've done this using the command `pip3 install -e .` as well as the command `pip3 install pymagsac==0.2.0`. Side note: the command in the github site `pip3 install magsac` produces the error `ERROR: No matching distribution found for magsac`

However, when importing in python, I get the following error:
`>>> import pymagsac
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "magsac/src/pymagsac/__init__.py", line 1, in <module>
    from .pymagsac import *
ModuleNotFoundError: No module named 'pymagsac.pymagsac'`

For what it's worth, I was unable to install using `python3 ./setup.py install` or `cmake` due to local issues, so I can't say for sure those would have worked for me.

Thanks for your support, apologies if I've missed something obvious!
Chris

**Comment by crockwell** [comment]
Worked when I switched to OpenCV 3.4.16.57 -- did not work on 4.4.0
